name = "sport-community-online"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "sport-community-online"

[env.development]
name = "sport-community-online-dev"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "sport-community-db"
database_id = "your-database-id-here"

# Environment Variables
[vars]
ENVIRONMENT = "development"

# Pages Configuration for Frontend
[build]
command = "npm run build"
cwd = "."
destination_dir = "dist"