// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krxbnccnqkauddzyyaeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyeGJuY2NucWthdWRkenl5YWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTM5MTcsImV4cCI6MjA2MzEyOTkxN30.DTa7gxIUjmg8010Eh4Q_0JZNo634pIHbotfiP0zkVpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);